config/routes.rb
Rails.application.routes.draw do
  resources :smartpages
  get 'script/test', to: 'script#test', :defaults => { format: :js }
  # post 'smartpages', to: 'home#smartpages'
  root :to => 'home#index'
  mount ShopifyApp::Engine, at: '/'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/shop.rb
# frozen_string_literal: true
class Shop < ActiveRecord::Base
  include ShopifyApp::ShopSessionStorage

  def api_version
    ShopifyApp.configuration.api_version
  end

  has_many :smartpages
end

app/models/smartpage.rb
class Smartpage < ApplicationRecord
  belongs_to :shop
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  after_action :allow_shopify_iframe

  private

  def allow_shopify_iframe
    response.headers['X-Frame-Options'] = 'ALLOWALL'
  end
end

app/controllers/authenticated_controller.rb
# frozen_string_literal: true

class AuthenticatedController < ApplicationController
  include ShopifyApp::Authenticated
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < AuthenticatedController
  def index
    find_thrive_data_snippet
    create_thrive_data_snippet
    include_thrive_data_snippet
  end

  def find_thrive_data_snippet
    # find previous version of our snippet and destroy it.
    # if not found create new, catch error to create new.
    begin
      @thrive_liquid = ShopifyAPI::Asset.find("snippets/thrive.liquid")
      @thrive_liquid.destroy
    rescue ActiveResource::ResourceNotFound => e
      Rails.logger.info("Could not find Trhive snippet. Creating new.")
    rescue Exception => e
      Rails.logger.info("Could not complete search for Thrive snippet. #{e.message}")
    end
  end

  def create_thrive_data_snippet
    @thrive_liquid = ShopifyAPI::Asset.new
    rendered_snippet = render_to_string("shopify_snippets/thrive.liquid", layout: false)
    @thrive_liquid.value = rendered_snippet
    @thrive_liquid.key = "snippets/thrive.liquid"
    @thrive_liquid.save
  end

  def include_thrive_data_snippet
    # get main theme liquid file and its html
    theme_liquid = ShopifyAPI::Asset.find("layout/theme.liquid")
    theme_liquid_html = theme_liquid.value
    # find head tag in html
    # append with render statement for our snippet if it is not already there. 
    # content of snippit can change because it is loaded into templates dynamically
    # and we replace the content of the snippet file with snippets/thrive.liquid on visit to our app's root in shopify admin.
    render_snippet_html = "{% render 'thrive' %}"
    if theme_liquid_html.index(render_snippet_html).nil?
      head_location = theme_liquid_html.index('<head>') + '<head>'.length
      theme_liquid_html.insert(head_location, render_snippet_html)
      theme_liquid.value = theme_liquid_html
      theme_liquid.save
    end
  end
end

app/controllers/script_controller.rb
class ScriptController < ActionController::Base
  protect_from_forgery except: :test
end

app/controllers/smartpages_controller.rb
class SmartpagesController < AuthenticatedController
  before_action :set_smartpage, only: [:show, :edit, :update, :destroy]
  before_action :set_shop

  # GET /smartpages
  # GET /smartpages.json
  def index
    @smartpages = Smartpage.all
  end

  # GET /smartpages/1
  # GET /smartpages/1.json
  def show
  end

  # GET /smartpages/new
  def new
    @smartpage = Smartpage.new
  end

  # GET /smartpages/1/edit
  def edit
  end

  # POST /smartpages
  # POST /smartpages.json
  def create
    @smartpage = Smartpage.new(smartpage_params)
    @smartpage.shop_id = @shop.id if @shop

    respond_to do |format|
      if @shop == nil
        format.html { render :new, notice: 'Shop not found. Please log out and log back in again.' }
        format.json { render json: @smartpage.errors, status: :unprocessable_entity }
      elsif @smartpage.save
        # if no page here, then this is a new smartpage. else delete it. 
        page = shopify_find_smartpage(@smartpage.path)
        delete_response = shopify_delete_smartpage(page) if page
        new_shopify_page = shopify_create_smartpage(@smartpage.path)
        if new_shopify_page.save
          format.html { redirect_to @smartpage, notice: 'Smartpage was successfully created.' }
          format.json { render :show, status: :created, location: @smartpage }
        else
          format.html { render :edit, notice: "Error creating new Shopify page. Original page: #{page} Delete response: #{delete_response}" }
          format.json { render json: new_shopify_page.errors, status: :unprocessable_entity }
        end
      else
        format.html { render :new }
        format.json { render json: @smartpage.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /smartpages/1
  # PATCH/PUT /smartpages/1.json
  def update
    respond_to do |format|
      old_handle = @smartpage.path
      if @smartpage.update(smartpage_params)
        # if we are updating our smartpage db record for this shop, 
        # we find the page, delete it if it exists and then recreate. 
        page = shopify_find_smartpage(old_handle)
        delete_response = shopify_delete_smartpage(page) if page
        new_shopify_page = shopify_create_smartpage(@smartpage.path)
        if new_shopify_page.save
          format.html { redirect_to @smartpage, notice: 'Smartpage was successfully updated.' }
          format.json { render :show, status: :ok, location: @smartpage }
        else
          format.html { render :edit, notice: "Error creating new Shopify page. Original page: #{page} Delete response: #{delete_response}" }
          format.json { render json: new_shopify_page.errors, status: :unprocessable_entity }
        end
      else
        format.html { render :edit }
        format.json { render json: @smartpage.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /smartpages/1
  # DELETE /smartpages/1.json
  def destroy
    @smartpage.destroy
    page = shopify_find_smartpage(@smartpage.path)
    delete_response = shopify_delete_smartpage(page) if page
    respond_to do |format|
      if page == nil
        format.html { redirect_to smartpages_url, notice: 'Smartpage was successfully destroyed, but did not exist in merchant store.' }
        format.json { head :no_content }
      elsif delete_response && delete_response.code == '200'
        format.html { redirect_to smartpages_url, notice: 'Smartpage was successfully destroyed.' }
        format.json { head :no_content }
      else
        format.html { redirect_to smartpages_url, notice: "Error: Could not destroy. Smartpage: #{@smartpage.errors} Page: #{page} Delete Response: #{delete_response}" }
        format.json { head :no_content }
      end
    end
  end

  private
    def shopify_find_smartpage(path)
      ShopifyAPI::Page.where(handle: path).first
    end


    def shopify_delete_smartpage(page)
      ShopifyAPI::Page.delete(page.id)
    end


    def shopify_create_smartpage(path)
      page = ShopifyAPI::Page.new(handle: path, title: "&nbsp;")
      script = "<script src='//integrate.thrive.today'></script>"
      page.body_html = script
      page.save
      page
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_smartpage
      @smartpage = Smartpage.find(params[:id])
    end

    def set_shop
      @shop = Shop.where(id: session['shop_id']).first
    end

    # Only allow a list of trusted parameters through.
    def smartpage_params
      params.require(:smartpage).permit(:path)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/smartpages_helper.rb
module SmartpagesHelper
end

app/views/home/index.html.erb
<h2>Welcome to Thrive!</h2>

<a href="https://frontend-management-stage.tcapi.io/">Navigate to our Promotions Manager to create a new Promotions Center!</a>

<p>To manage your Smartpages in Shopify, use the links below:</p>

<%= link_to 'New Smartpage', new_smartpage_path %> | 
<%= link_to 'View All Smartpages', smartpages_path %>

app/views/layouts/_flash_messages.html.erb
<% content_for :javascript do %>
  <%= content_tag(:div, nil, id: 'shopify-app-flash', data: { flash: { notice: flash[:notice], error: flash[:error] } }) %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ThriveShopifyDev</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/embedded_app.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <% application_name = ShopifyApp.configuration.application_name %>
    <title><%= application_name %></title>
    <%= stylesheet_link_tag 'application' %>
    <% if ShopifyApp.use_webpacker? %>
      <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <% else %>
      <%= javascript_include_tag 'application', "data-turbolinks-track" => true %>
    <% end %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div class="app-wrapper">
      <div class="app-content">
        <main role="main">
          <%= yield %>
        </main>
      </div>
    </div>

    <%= render 'layouts/flash_messages' %>

    <script src="https://unpkg.com/@shopify/app-bridge"></script>

    <%= content_tag(:div, nil, id: 'shopify-app-init', data: {
      api_key: ShopifyApp.configuration.api_key,
      shop_origin: (@current_shopify_session.domain if @current_shopify_session),
      debug: Rails.env.development?
    } ) %>

    <% if content_for?(:javascript) %>
      <div id="ContentForJavascript" data-turbolinks-temporary>
        <%= yield :javascript %>
      </div>
    <% end %>
  </body>
</html>

app/views/script/test.js.erb
// console.log('yo');
// jQuery.getJSON('/cart.js', function(cart) {
 
//     let items = cart.items;

// 	console.log('There are ' + items.length + ' items in the cart.'); 
// 	for(var i=0; i < items.length; i++){
// 		console.log(items[i].title);
// 	}
// 	console.log(cart);

// 	// jQuery.post('/cart/update.js', {
// 	//   updates: {
	    
// 	//   }
// 	// });

// });

app/views/smartpages/_form.html.erb
<%= form_with(model: smartpage, local: true) do |form| %>
  <% if smartpage.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(smartpage.errors.count, "error") %> prohibited this smartpage from being saved:</h2>

      <ul>
        <% smartpage.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :path %>
    <%= form.text_field :path %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/smartpages/edit.html.erb
<p id="notice"><%= notice %></p>
<h1>Editing Smartpage</h1>

<%= render 'form', smartpage: @smartpage %>

<%= link_to 'Show', @smartpage %> |
<%= link_to 'View All Smartpages', smartpages_path %>

app/views/smartpages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Smartpages</h1>

<% if @smartpages.count == 0 %>
  <p>You haven't created any Smartpages yet!</p>
<% else %>
  <table>
    <thead>
      <tr>
        <th>Path</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @smartpages.each do |smartpage| %>
        <tr>
          <td><%= smartpage.path %></td>
          <td><%= link_to 'Show', smartpage %></td>
          <td><%= link_to 'Edit', edit_smartpage_path(smartpage) %></td>
          <td><%= link_to 'Destroy', smartpage, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>
<br>

<%= link_to 'New Smartpage', new_smartpage_path %>

app/views/smartpages/new.html.erb
<p id="notice"><%= notice %></p>

<h1>New Smartpage</h1>

<%= render 'form', smartpage: @smartpage %>

<%= link_to 'View All Smartpages', smartpages_path %>

app/views/smartpages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Path:</strong>
  <%= @smartpage.path %>
</p>

<%= link_to 'Edit', edit_smartpage_path(@smartpage) %> |
<%= link_to 'View All Smartpages', smartpages_path %>